### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by cauerego**
pretty self explanatory, found both because console were pointing the errors.

### CODE REVIEW

**Comment by cauerego** [comment]
the fix for the "bug" on navbar (pushed quite after my last comment) I found when trying to add a bigger image to it

**Comment by dkenzik** [comment]
@paolotripodi - Can you pull this when you get a chance?

**Comment by paolotripodi** [comment]
@cauerego sorry for delayed answer, so much work :) thanks for your fixes!

**Comment by cauerego** [comment]
I'm really glad they helped! :)

**Pull request merged**
